### DISCUSSION TITLE
Werf build through Argo Workflows

### DISCUSSION THREAD

**Discussion by Matthias64** [werf/werf#3616] [General]
Hello, 

Currently we are using Werf to build our project. The build is handled by Jenkins and it's working all fine. 

We are trying to switch from Jenkins to Argo. We have created a Github webhook that triggers an Argo Workflow that runs werf command. But we are facing an issue when the werf build command is ran through Argo workflow. 

The error we are facing is 
```
│ ┌ Building stage core/gitArchive
│ │ core/gitArchive  /.werf/stapel/embedded/bin/bash:                                                   ↵
│ │ core/gitArchive  /.werf/scripts/4df85bb1cda0b78fb09c506919a488a70acc69b691adb2440ee4d968c619feb8:   ↵
│ │ core/gitArchive  No such file or directory
│ ├ Info
│ └ Building stage core/gitArchive (0.94 seconds) FAILED
└ ⛵ image core (1.12 seconds) FAILED
``` 

Here is a simplied version of the workflow we are using : 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow   # Type defined by argo-workflows
metadata:
  generateName: build-workflow-    # Workflow Name
spec:
  serviceAccountName: argoworkflows-account  # Argo workflow account created through Terraform
  entrypoint: build-and-push
  arguments:
    parameters:
      - name: repo
        value: REPO
      - name: branch
        value: BRANCH_NAME

  templates:
    - name: build-and-push
      steps:
        - - name: werf-build
            template: werf-build

    - name: werf-build
      inputs:
        artifacts:
          - name: source
            path: /src
            git:
              repo: "{{workflow.parameters.repo}}"
              revision: "{{workflow.parameters.branch}}"
              sshPrivateKeySecret:
                name: XXXXX-backend
                key: sshPrivateKey
      sidecars:
        # Sidecar dind (docker in docker) is used to have a docker daemon available
        - name: dind
          image: docker:20.10.6-dind
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          securityContext:
            privileged: true
          mirrorVolumeMounts: true
      container:
        image: docker:20.10.6
        command: [sh, -c]
        env:
          - name: DOCKER_HOST  # Docker daemon sidecar location
            value: 127.0.0.1
          - name: AWS_REGISTRY_ID
            value: "XXXX"
          - name: AWS_REGISTRY_REGION
            value: "XXXX"
          - name: AWS_ECR_PASSWORD
            value: "XXXX"
        # The loop before werf build is to avoid docker daemon error when the daemon is not ready yet.
        args: ["
          echo {{inputs.parameters.AWS_ECR_PASSWORD}} | docker login --username AWS --password-stdin ${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGISTRY_REGION}.amazonaws.com &&
          cd /src && apk add --no-cache curl git jq &&
          curl https://storage.yandexcloud.net/werf/targets/releases/v1.2.10+fix29/werf-linux-amd64-v1.2.10+fix29 -o /usr/local/bin/werf &&
          chmod +x /usr/local/bin/werf &&
          until docker ps; do sleep 3; done &&
          werf build --log-verbose=true --report-format=json --repo=${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGISTRY_REGION}.amazonaws.com/backend/stages
        "]
```

For me this seems to be an issue with the docker in docker usage. I found [this issue](https://github.com/werf/werf/issues/1462) that seems to be similar. In particular it states that werf and docker have to run on the same host. I have tried to do that by using a Linux Alpine image instead and installing docker manually there but it was not conclusive.

```
│ ├ Info
│ └ Building stage base-django/dockerfile (2.34 seconds) FAILED
└ ⛵ image base-django (3.28 seconds) FAILED

Running time 4.60 seconds
Error: phase build on image base-django stage dockerfile handler failed: failed to build image for stage dockerfile with digest 6806870d433110a53ff7568a16f896ed50d1904a048ed3958dfb6a09: Status: The command '/bin/sh -c apt update   && apt -y upgrade   && apt install -y --no-install-recommends   build-essential   curl   gettext   git   gnupg2   libffi-dev   libpq-dev   libssl-dev   libturbojpeg-dev   libxml2-dev   libxslt-dev   libyaml-dev   lsb-release   wget   zlib1g-dev   && apt clean' returned a non-zero code: 100, Code: 100
```

Would you have any idea on that issue ? Have you ever run werf build on a docker container ? 

Thank you !

**Comment by distorhead** [comment]
Hi!

> No such file or directory

This error occurs because stapel images builder uses volume mounts to pass service files into build container.

Werf currently requires `/tmp` and `~/.werf` directories to be the same on docker host and the host running werf process.

There is also an open issue: https://github.com/werf/werf/issues/1926

**Reply by Matthias64** [reply]
Hi ! 
Thanks for your reply, I tried to mount both folders and still face the same issue, I must be missing something else.
With the option `mirrorVolumeMounts: true`, it should  mount the same volumes specified in the main container to the docker sidecar. I also tried to mount the werf directory to `/root/.werf` without the `--home-dir` option but that did not work neither.


```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow   # Type defined by argo-workflows
metadata:
  generateName: build-workflow-    # Workflow Name
spec:
  serviceAccountName: argoworkflows-account  # Argo workflow account created through Terraform
  entrypoint: build-and-push
  volumes:
    - name: werf-cache
      hostPath:
        path: /.werf
    - name: tmp
      hostPath:
        path: /tmp
  arguments:
    parameters:
      - name: repo
        value: REPO
      - name: branch
        value: BRANCH_NAME

  templates:
    - name: build-and-push
      steps:
        - - name: werf-build
            template: werf-build

    - name: werf-build
      inputs:
        artifacts:
          - name: source
            path: /src
            git:
              repo: "{{workflow.parameters.repo}}"
              revision: "{{workflow.parameters.branch}}"
              sshPrivateKeySecret:
                name: XXXXX-backend
                key: sshPrivateKey
      sidecars:
        # Sidecar dind (docker in docker) is used to have a docker daemon available
        - name: dind
          image: docker:20.10.6-dind
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          securityContext:
            privileged: true
          mirrorVolumeMounts: true
      container:
        image: docker:20.10.6
        command: [sh, -c]
        volumeMounts:
          - name: werf-cache
            mountPath: /.werf
          - name: tmp
            mountPath: /tmp
        env:
          - name: DOCKER_HOST  # Docker daemon sidecar location
            value: 127.0.0.1
          - name: AWS_REGISTRY_ID
            value: "XXXX"
          - name: AWS_REGISTRY_REGION
            value: "XXXX"
          - name: AWS_ECR_PASSWORD
            value: "XXXX"
        # The loop before werf build is to avoid docker daemon error when the daemon is not ready yet.
        args: ["
          echo {{inputs.parameters.AWS_ECR_PASSWORD}} | docker login --username AWS --password-stdin ${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGISTRY_REGION}.amazonaws.com &&
          cd /src && apk add --no-cache curl git jq &&
          curl https://storage.yandexcloud.net/werf/targets/releases/v1.2.10+fix29/werf-linux-amd64-v1.2.10+fix29 -o /usr/local/bin/werf &&
          chmod +x /usr/local/bin/werf &&
          until docker ps; do sleep 3; done &&
          werf build --log-verbose=true --report-format=json --report-path=kolibree-backend.json --home-dir=/.werf --repo=${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGISTRY_REGION}.amazonaws.com/backend/stages
        "]
```

```
│ ┌ Building stage kml/install
│ │ kml/install  /.werf/shell/script.sh: line 4: t*6%: No such file or directory
│ ├ Info
│ └ Building stage kml/install (0.98 seconds) FAILED
└ ⛵ image kml (24.26 seconds) FAILED
```
