### DISCUSSION TITLE
How to avoid download dependencies on source code changing?

### DISCUSSION THREAD

**Discussion by develar** [werf/werf#3634] [General]
I have a simple `werf.yaml` file. 

```
configVersion: 1
project: ij-developer-dashboard
---
image: backend
from: gcr.io/distroless/static-debian10
import:
  - artifact: backend-binary
    before: setup
    add: /bin/backend
---
artifact: backend-binary
from: golang:1.16.6-buster
git:
  - add: /cmd/backend
    to: /project/cmd/backend
  - add: /go.mod
    to: /project/go.mod
  - add: /go.sum
    to: /project/go.sum
shell:
  install:
    - cd /project && go mod download
  beforeSetup:
    - cd /project && go build -ldflags='-s -w -extldflags "-static"' -tags netgo -trimpath -o /bin/backend ./cmd/backend
```

The issue — if `cmd/backend/backend.go` file is modified, I see 

> Building stage backend-binary/install (15.20 seconds)

But only `Building stage backend-binary/beforeSetup` is expected (rebuild app), since `go.sum` and `go.sum` are not modified.

I tried to use `  installCacheVersion: {{.Files.Get "go.mod" | sha256sum}}` — no luck.
I tried ` install: []` — no luck.

```
  - add: /cmd/backend
    to: /project/cmd/backend
    stageDependencies:
      install: []
```

So, how do I can configure werf to execute `backend-binary/beforeSetup` only if go.mod/go.sum files are changed?

**Comment by develar** [comment]
Looks like `amend` commit forces werf to rebuild entire stack.

And I found important note in docs https://werf.io/documentation/v1.2/advanced/building_images_with_stapel/artifacts.html#using-artifacts:

> Stapel artifact though is recommended to be used as a deeply cached image, which will be updated in rare cases,

Meaning `git.stageDependencies` is required.

Resulting `werf.yaml`:


```yaml
configVersion: 1
project: name
---
image: backend
from: gcr.io/distroless/static-debian10
import:
  - artifact: backend-binary
    before: setup
    add: /bin/backend
---
artifact: go-deps
from: golang:1.16.6-buster
git:
  - add: /go.mod
    to: /project/go.mod
    stageDependencies:
      install:
        - "*"
  - add: /go.sum
    to: /project/go.sum
    stageDependencies:
      install:
        - "*"
shell:
  install:
    - cd /project && go mod download
---
artifact: backend-binary
from: golang:1.16.6-buster
git:
  - add: /cmd/backend
    to: /project/cmd/backend
    stageDependencies:
      setup:
        - "*"
        - "**/*"
  - add: /go.mod
    to: /project/go.mod
  - add: /go.sum
    to: /project/go.sum
import:
  - artifact: go-deps
    before: setup
    add: /go
shell:
  setup:
    - cd /project && go build -ldflags='-s -w -extldflags "-static"' -tags netgo -trimpath -o /bin/backend ./cmd/backend
```

**Reply by alexey-igrychev** [reply]
Try this one:
```yaml
configVersion: 1
project: name
---

image: backend
from: gcr.io/distroless/static-debian10
import:
  - artifact: backend-binary
    before: setup
    add: /bin/backend
---
artifact: backend-binary
from: golang:1.16.6-buster
git:
  - add: /
    to: /project
    stageDependencies:
      install: 
        - go.mod
        - go.sum
      setup:
        - "**/*.go"
shell: 
  install: 
    - cd /project 
    - go mod download
  setup: 
    - cd /project
    - go build -ldflags='-s -w -extldflags "-static"' -tags netgo -trimpath -o /bin/backend ./cmd/backend
```
