### DISCUSSION TITLE
How I can use variables in werf.yaml file.

### DISCUSSION THREAD

**Discussion by ith-yurybebsh** [werf/werf#3914] [General]
Dear, colleagues.

Sorry for my English. Maybe somebody can help me.

I need to use the variable "env" in the file "werf.yaml". How I can do this without changes in "werf-giterminism.yaml".

For example werf.yaml:

```
configVersion: 1
project: example
---
artifact: builder
from: php:7.2-cli
git:
  - add: /source/
    to: /var/www
    stageDependencies:
      install:
        - "**/*"
      beforeSetup:
        - "**/*"
shell:
  install:
    - export ENVIRONMENT_NAME=--THIS--PLACE--FOR--USING--
    - cd /var/www/
    - php build.php
```

I try to replace --THIS--PLACE--FOR--USING-- for:
- $env
- [[ env ]]
- {{ .Values.env }}

It's necessary for building. I will be glad any information about opportunities using variables.

At now I use "werf-giterminism.yaml" and option "allowUncommitted: true".
In Github action do 
```
 - name: Replace environment in the werf.yaml file
        env:
          ENVIRONMENT_NAME: "${{ env.ENVIRONMENT_NAME }}"
        run: |
          cat werf.yaml.in | envsubst > werf.yaml
          cat werf.yaml
```

After that, I run converge action. But it is a solution don't like. I what to use env variable, what I set in converge stage:
```
- name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: ${{ env.ENVIRONMENT_NAME }}
          kube-config-base64-data: ${{ env.KUBE_CONFIG }}
```

Thanks

**Comment by alexey-igrychev** [comment]
When configuring the build for different environments, you can use `{{ .Env }}` ([more here](https://werf.io/documentation/v1.2/reference/werf_yaml_template_engine.html#various-environments)) which corresponds to the value `--env=<env>` or `env` input in actions.

You can also use environment variables with `{{ env "<ENV_NAME>" }}` ([more here](https://werf.io/documentation/v1.2/reference/werf_yaml_template_engine.html#environment-variables)).

**UPD**: `{{ .env }}` => `{{ .Env }}`

**Reply by ith-yurybebsh** [reply]
Thanks for your answer.
But maybe I understand something wrong.

When I use {{ env "env" }} I got the error "<env "env">: error calling env: the configuration with potential external dependency found in the werf config: env name "env" not allowed by giterminism"
So, for this variant, I need to use file "werf-giterminism.yaml"

When I use ".env", got "no-value".
```
    - echo "{{ .env }}" > /var/www/build/debug
    - echo "{{ .env.env }}" >> /var/www/build/debug
    - echo "{{ .env.ENVIRONMENT_NAME }}" >> /var/www/build/debug
```

My CD.yaml, step converge:
```
- name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: ${{ env.ENVIRONMENT_NAME }}
          kube-config-base64-data: ${{ env.KUBE_CONFIG }}
        env:
          WERF_SET_ENVIRONMENT_NAME: "ENVIRONMENT_NAME=${{ env.ENVIRONMENT_NAME }}"
          WERF_SET_CLOUD_PROVIDER: "CLOUD_PROVIDER=${{ env.CLOUD_PROVIDER }}"
          WERF_SET_KUBE_NAMESPACE: "KUBE_NAMESPACE=${{ env.NAMESPACE }}"

          WERF_PARALLEL_TASKS_LIMIT: 1
```

P.s. I  need to use "env" for the shell commands in "werf.yaml".
