### DISCUSSION TITLE
helmfile issues with werf

### DISCUSSION THREAD

**Discussion by MxNxPx** [werf/werf#4154] [General]
hi all,
when utilizing helmfile with `werf` as the helm binary, I am not getting the same experience as using `helm` as the helm binary.  in particular i am trying to get it to work with the "raw" chart from [here](https://github.com/paulczar/helmfile-starter-kit#creating-one-off-custom-resources-for-charts).

here is my repo with the setup:
https://github.com/MxNxPx/helmfile-example

when i run helmfile with `--debug` i see the resulting werf command is this:
```
exec: werf diff upgrade --reset-values --allow-unreleased test-raw paulczar/raw --version 1.0.1 --namespace default --values /tmp/helmfile327923360/default-test-raw-values-5ff77bf8b9 --detailed-exitcode
```
running that command through werf directly (with the necessary values file) gives the same result as through helmfile, the diff doesn't see a change needed and exits
```console
$ cat <<EOF >> /tmp/test-raw-values.yaml
> manifests:
>   - metadata:
>       name: helmfile-cm
>     apiVersion: v1
>     kind: ConfigMap
>     data:
>       data-key-1: data-value-1
> EOF
export WERF_HELM3_MODE=1
$ werf diff upgrade --reset-values --allow-unreleased test-raw paulczar/raw --version 1.0.1 --namespace default --values /tmp/test-raw-values.yaml --detailed-exitcode
********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
```

but running that same command using helm directly instead of werf, it works as desired, spotting the difference and proposing a change be made
```console
$ helm diff upgrade --reset-values --allow-unreleased test-raw paulczar/raw --version 1.0.1 --namespace default --values /tmp/test-raw-values.yaml --detailed-exitcode
********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
default, helmfile-cm, ConfigMap (v1) has been added:
- 
+ # Source: raw/templates/manifests.yaml
+ apiVersion: v1
+ data:
+   data-key-1: data-value-1
+ kind: ConfigMap
+ metadata:
+   annotations: {}
+   labels:
+     app.kubernetes.io/instance: test-raw
+     app.kubernetes.io/managed-by: Helm
+     app.kubernetes.io/name: raw
+     app.kubernetes.io/version: "1.0"
+     helm.sh/chart: raw-1.0.1
+   name: helmfile-cm
+   namespace: default
Error: identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)
Error: plugin "diff" exited with error
```

any thoughts on what may be causing this behavior?  or suggestions on how to troubleshoot this further?

thanks!

**Comment by distorhead** [comment]
Hi! It is possible that helmfile + werf has been broken since some release, because we doesn't have special tests for this case of usage. We will try to investigate this case this week.

**Comment by distorhead** [comment]
Hi!

Find out that helm-diff `manifest.Parse` function could not parse output of `werf template`, but parses output of `helm template`.

`werf template` output:

```
# Source: raw/templates/manifests.yaml
apiVersion: v1
data:
  data-key-1: data-value-1
kind: ConfigMap
metadata:
  annotations:
    werf.io/version: dev
  labels:
    app.kubernetes.io/instance: test-raw
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: raw
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: raw-1.0.1
  name: helmfile-cm
  namespace: default

```

`helm template` output:

```
---
# Source: raw/templates/manifests.yaml
apiVersion: v1
data:
  data-key-1: data-value-1
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: test-raw
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: raw
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: raw-1.0.1
  name: helmfile-cm
  namespace: default

```

There are not much differences: three hyphens before manifest in the case of helm and additional annotation in the case of werf.
 At the moment have no idea why manifest.Parse refuses to parse werf output.

By the way, werf's output is a little different, because it uses builtin post-renderer to inject custom annotations and labels into all deployed resources.
