### DISCUSSION TITLE
werf new feature: External dependencies before deploying

### DISCUSSION THREAD

**Discussion by shurup** [werf/werf#4595] [Announcements]
### Briefly

* Feature: Wait for an external Kubernetes resource to be ready before deploying the release resource.
* Version: **v1.2.121**+ (alpha).
* PR: #4543.

### Background
werf already supports defining dependencies between resources within a single werf converge process by specifying the deployment order using `werf.io/weight`. However, up until now, there has been no way to wait for the readiness of resources that are not part of the current release (or deployed by other means).

### Details
You can configure out-of-release Kubernetes resource dependencies using the following annotations:
* `xxx.external-dependency.werf.io/resource: resource[.version[.group]]/name` — set the external dependency;
* `xxx.external-dependency.werf.io/namespace` — specify the namespace of the external resource (if different from the release namespace).

### Example
```
kind: Deployment
metadata:
  name: frontend
  annotations:
    secret.external-dependency.werf.io/resource: "secret/dynamic-vault-secret"
    backend.external-dependency.werf.io/resource: "deployment/backend"
    backend.external-dependency.werf.io/namespace: "production-backend"
```

In the above example, when `werf converge` is executed, the `frontend` resource will not commence deployment until the `dynamic-vault-secret` Secret and the `backend` Deployment in the `production-backend` namespace are created and `Ready` (provided they have this status).
