### DISCUSSION TITLE
Werf import files from external image

### DISCUSSION THREAD

**Discussion by dmitryuk** [werf/werf#4697] [General]
Hello. I want to add binary to my build.
Command: `werf build –stages-storage=:local --dev`
werf.yaml
```yaml
project: online-backend
configVersion: 1
deploy:
  namespaceSlug: false
---
image: backend
docker:
  WORKDIR: /var/www
from: php:8.1.0-fpm-alpine3.15
import:
  - image: composer:2.3
    add: /usr/bin/composer
    to: /usr/bin/composer
    before: install
```

But I get the error: `Error: unable to load werf config: no such image ``!` (yes with empty image name)

What's wrong?
werf v1.2.140

**Comment by ilya-lesikov** [comment]
`import` directive works in a different way: it is used to import artifacts from another image that is defined in the same `werf.yaml`. You should do something like this:
```yaml
---
image: composer
from: composer:2.3
---
image: backend
from: php:8.1.0-fpm-alpine3.15
import:
  - image: composer
    add: /usr/bin/composer
    to: /usr/bin/composer
    before: install
```

Or, honestly, maybe there is a better way to install composer?

We'll fix the error message.
