### DISCUSSION TITLE
Werf conditional install by arg

### DISCUSSION THREAD

**Discussion by dmitryuk** [werf/werf#4717] [General]
I have werf.yaml with shell script, that execute the code by environment variable value like:
```
#!/bin/sh
if [ "${WITH_XDEBUG}" = "true" ] ; then 
# do some magic here
fi
```

How to pass any readable environment variable during `werf build` command? 
I'm looking something like:
`WITH_XDEBUG=true werf build `

**Comment by ilya-lesikov** [comment]
You should explicitly allow every environment variable you are going to use using `werf-giterminism.yaml`:
```yaml
# werf-giterminism.yaml:
giterminismConfigVersion: 1
config:
  goTemplateRendering:
    allowEnvVariables:
    - WITH_XDEBUG
```

Now you can use this variable in your werf.yaml:
```yaml
# werf.yaml
...
shell:
  beforeInstall:
  - echo {{ env "WITH_XDEBUG" }}
```

Command:
```shell
WITH_XDEBUG=true werf build
```

https://werf.io/documentation/v1.2/advanced/giterminism.html#env
