### DISCUSSION TITLE
DNS resolution failed

### DISCUSSION THREAD

**Discussion by dmitryuk** [werf/werf#5094] [General]
Hello. We are migrating local development environment from `docker-compose` to `werf compose`. All working fine on some users, but some faced with DNS resolution issue.
Docker-compose had `network: host` flag and it worked fine:
```
version: '3.8'
services:
  backend:
    build:
      # ...
      network: host
``` 

I can't set `network: host` while building or what to do?
