### DISCUSSION TITLE
werf new feature: Building multi-platform container images (v1.2.232+)

### DISCUSSION THREAD

**Discussion by shurup** [werf/werf#5642] [Announcements]
### Briefly

werf now supports building images for any platform and for multiple platforms out of the box.

_This feature became available starting from werf v1.2.232, which is currently in the Early-Access release channel._

All you have to do is to declare a list of target platforms for all images in the configuration and run `werf build` (or `werf converge`, or any other command that uses the image build) — werf will take care of the rest. It will:

- build and publish images for each of the target platforms using a cross-platform emulation mechanism;
- publish the final multiplatform meta-image for future use;
- automatically add tags to both the platform-specific images and the final multi-platform image;
- provide you with the option to use arbitrary custom tags instead of automatic tags for the final multi-platform image;
- clean up unused images based on Git history.

### Configuration

```
project: example
configVersion: 1
build:
  platform:
  - linux/arm64
  - linux/amd64
---
image: first
dockerfile: Dockerfile.first
staged: true
---
image: second
dockerfile: Dockerfile.second
platform:
- linux/amd64
staged: true
---
image: third
from: alpine
shell:
  install:
  - apk add curl gnupg
```

werf supports:

- specifying a generic list of target platforms with the `build.platform` directive;
- specifying a target platform list for individual images with the `platform` directive in the `image` context;
- overriding the target platform list using the `--platform=linux/amd64,linux/arm64,...` CLI parameter.

[More on configuration →](https://werf.io/documentation/v1.2.232/usage/build/images.html#multi-platform-and-cross-platform-building)

### Features and limitations

werf supports:

- layer-by-layer Dockerfile builds and single-layer builds using the Buildah backend;
- building Stapel images using the Buildah backend;
- building Dockerfiles in a single layer using the BuildKit backend.

**We recommend using the Buildah backend** since it has the most comprehensive backend support for all builders.

Read more on:
-  [builder support](https://werf.io/documentation/v1.2.232/usage/build/process.html#multi-platform-builds);
- [preparing the system](https://werf.io/documentation/v1.2.232/index.html?usage=localDev&os=linux&buildBackend=buildah).
