### DISCUSSION TITLE
How to use the GitHub Cache action to speed up builds

### DISCUSSION THREAD

**Discussion by ma9o** [werf/werf#6340] [General]
Hi, one of the base images in my `werf.yaml` is multiple GBs in size and the runner takes a few minutes to download it each time the setup stage of the dependent image has to be rebuilt. 

In my GHA workflow I'd like to pre-pull such base image and store/restore it in the cache, but I'm getting a bunch of errors like this one in the post of the cache action: `/usr/bin/tar: ../../../.local/share/containers/storage/overlay/672faccf8544f74609035b701e7e5624af45e83d9638194919cfb53cff3b98e9/diff/home/rapids: Cannot open: Permission denied`

Has anyone else succeeded in this? Can this be configured in werf itself?

.github/workflows/ci.yml
```yaml
- uses: actions/cache@v4
  name: Buildah cache
  with:
    key: ${{ runner.os }}-buildah-
    path: |
      ~/.buildah-cache

- name: Pull base images
  run: |
    mkdir -p ~/.buildah-cache
    mv ~/.buildah-cache/ ~/.local/share/containers/storage/
    buildah pull rapidsai/base:24.04-cuda12.2-py3.11
    mv ~/.local/share/containers/storage/ ~/.buildah-cache/
```

werf.yaml
```yaml
image: data-pipeline-rapids
from: rapidsai/base:24.04-cuda12.2-py3.11
git:
  - add: /apps/data-pipeline
    to: /app
    stageDependencies:
      install:
        - requirements.prod.txt
      setup:
        - '**/*.py'
shell:
  install:
    - /bin/bash --login
    - /opt/conda/bin/pip install --no-cache-dir -r /app/requirements.prod.txt
  setup:
    - /bin/bash --login
    - /opt/conda/bin/pip install --no-deps /app/dist/*.whl
docker:
  WORKDIR: /app
  ENV:
    HF_HOME: /model-cache/huggingface
    SENTENCE_TRANSFORMERS_HOME: /model-cache/sentence-transformers
mount:
  - fromPath: ./apps/data-pipeline/dist
    to: /app/dist
```
