### DISCUSSION TITLE
werf new release: v2.14.0 with secrets support for Dockerfiles

### DISCUSSION THREAD

**Discussion by shurup** [werf/werf#6447] [Announcements]
### Briefly

werf v2.14.0 has been released. It introduces initial support for build secrets.

### Background & details

The most notable changes for this release include:

- Support for build-time secrets when Dockerfiles are used with Docker and Buildah. Secret support for the Stapel builder and staged Dockerfiles is coming.
- Cleaning up the container registry for the images built by Buildah now behaves as intended.
- werf images are now published for the `linux/arm64` architecture as well.

### Configuration examples

Below is an example of werf configuration illustrating how build-time secrets can be used.

`werf.yaml`:
```
project: example
configVersion: 1
---
image: backend
dockerfile: Dockerfile
secrets:
  - env: AWS_ACCESS_KEY_ID
  - id: aws_secret_key
    env: AWS_SECRET_ACCESS_KEY
  - src: /user/foobar/.aws/credentials
  - id: plainSecret
    value: plainSecretValue
```

`werf-giterminism.yaml`:
```
giterminismConfigVersion: 1
config:
  secrets:
    allowEnvVariables: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    allowFiles: ["/user/foobar/.aws/credentials"]
```

`Dockerfile`:
```
FROM alpine:3.18

# Example of using a secret that is stored in an environment variable
RUN --mount=type=secret,id=AWS_ACCESS_KEY_ID \
    export ACCESS_KEY=$(cat /run/secrets/AWS_ACCESS_KEY_ID) && \
    echo "Using AWS Access Key: ${ACCESS_KEY}"

# Example of using a secret that is stored in a secret file
RUN --mount=type=secret,id=aws_secret_key \
    export SECRET_KEY=$(cat /run/secrets/aws_secret_key) && \
    echo "Using AWS Secret Key: ${SECRET_KEY}"

# Example of using a secret that is stored as an arbitrary value
RUN --mount=type=secret,id=plainSecret \
    export PLAIN_SECRET=$(cat /run/secrets/plainSecret) && \
    echo "Using plain secret: ${PLAIN_SECRET}"
```

### Additional information

* [v2.14.0 release](https://github.com/werf/werf/releases/tag/v2.14.0).
* [Using build secrets](https://werf.io/docs/v2/usage/build/images.html#using-build-secrets) documentation.
* #6373
