### DISCUSSION TITLE
How does "--atomic" work for werf converge

### DISCUSSION THREAD

**Discussion by meistuss** [werf/werf#6493] [General]
### Before proceeding
 * [x]  I didn't find a similar [issue](https://github.com/werf/werf/issues)
 
 ### Problem
werf converge doesn't try to rollback.
werf version:  v2.13.1
```bash
  werf converge
      --release ${<ENV>}
      --kube-config-base64 ${<ENV>}
      --repo ${<ENV>}
      --atomic true
      --add-custom-tag ${<ENV>}
      --set <values>
      --log-debug true
```
`werf.yaml`:
```yaml
project: airflow
configVersion: 1
cleanup:
  disableGitHistoryBasedPolicy: true
---
image: airflow
dockerfile: Dockerfile
staged: true
contextAddFiles:
- requirements/
args:
  AIRFLOW_VERSION: {{ env "AIRFLOW_VERSION" }}
  PYTHON_VERSION: {{ env "PYTHON_VERSION" }}
```
`Dockerfile`:
```dockerfile
ARG AIRFLOW_VERSION
ARG PYTHON_VERSION
FROM apache/airflow:slim-${AIRFLOW_VERSION}-python${PYTHON_VERSION}
...
```

`werf-giterminism.yaml` :
```yaml
giterminismConfigVersion: 1
config:
  allowUncommitted: true
  goTemplateRendering:
    allowEnvVariables:
      - AIRFLOW_VERSION
      - PYTHON_VERSION
  dockerfile:
    allowContextAddFiles:
    - requirements/
```
![werf](https://github.com/user-attachments/assets/9c62ec3e-4836-425e-b570-ab756fa5b02f)

 Does "--atomic" option have restrictions or can't be used with special options? What do I do wrong?
