### DISCUSSION TITLE
Better imageSpec support in werf

### DISCUSSION THREAD

**Discussion by shurup** [werf/werf#6558] [Announcements]
We're excited to share our plans for improving how werf handles the OCI image format specification, [imageSpec](https://github.com/opencontainers/image-spec/blob/main/config.md).

### What’s coming to werf

- Full support for imageSpec, both globally and on a per-image basis.
- Standardizing the process across all backends (Buildah, Docker) and syntaxes (Dockerfile, Stapel).
- Deprecating the current `docker` directive in Stapel.

#### Global imageSpec configuration

- Adding the `author` field to all images.
- Stripping layer history from the final output image.
- Label management: adding and removing labels.

```
project: test
configVersion: 1
build:
  imageSpec:
    author: "John Doe <john.doe@example.com>"
    removeHistory: true
    config:
      removeLabels:
        - "unnecessary-label"
        - /org.opencontainers.image..*/
      labels:
        app: "my-app"
```

#### Configuring imageSpec for individual images

- Global settings are inherited and can be extended.
- All image configuration fields (such as `user`, `env`, `entrypoint`, `volumes`) are supported.
- Specific parameter (`volumes`, `env`, `labels`) values are removed.

```
image: frontend_image
imageSpec:
  author: "Frontend Maintainer <frontend@example.com>"
  removeHistory: true
  config:
    user: "1001:1001"
    exposedPorts:
      - "8080/tcp"
    env:
      NODE_ENV: "production"
      API_URL: "https://api.example.com"
    entrypoint:
      - "/usr/local/bin/start.sh"
    volumes:
      - "/app/data"
    workingDir: "/app"
    labels:
      frontend-version: "1.2.3"
    stopSignal: "SIGTERM"
    removeLabels:
      - "old-frontend-label"
      - /old-regex-label.*/
    removeVolumes:
      - "/var/cache"
    removeEnv:
      - "DEBUG"
```

#### Does modifying these parameters affect the build process?

Well, yes and no…

1. **No**, these directives won't let you alter settings like `workdir` or `user` that directly affect the Stapel image build process. However, we're looking to implement this in the future. For instance:

```
shell:
  setup:
    config: 
      env: 
        KEY: Value
      workdir: "/custom/workdir"
      user: "1001:1001"
    command:
      - echo 'setup completed'
```

2. **Yes**, you can create a dedicated base image in which you remove unnecessary `VOLUME` directives or introduce `ENV` variables. For instance:

```
image: base
from: postgres:12.22-bookworm
imageSpec:
  config:
    removeVolumes:
      - "/var/lib/postgresql/data"
---
image: app
fromImage: base
git:
  add: /postgresql/data
  to: /var/lib/postgresql/data
```

That's it for now. Your thoughts and suggestions are most welcome! ❤️

**Comment by shurup** [comment]
**The improved imageSpec (OCI Image Format Specification) support is available now!** The features described below were implemented throughout several werf releases, with the latest of them introduced in [v2.35.0](https://github.com/werf/werf/releases/tag/v2.35.0).

These changes mean you can flexibly manage the [OCI image configuration spec](https://github.com/opencontainers/image-spec/blob/main/config.md) of the images being built with werf. You can configure settings globally across your project or tailor them for individual images.

### Global imageSpec configuration

You can define the default image specification for all images:
```
project: my-project
configVersion: 1
build:
  imageSpec:
    author: "Dev Team <dev@example.com>"
    clearHistory: true
    config:
      labels:
        app: "my-app"
        owner: "team-x"
      removeLabels:
        - "legacy-label"
        - /org\.opencontainers\.image\..*/
```
### Per-image imageSpec configuration

You can override or extend global settings for specific images:
```
---
project: test
configVersion: 1
---
image: frontend_image
from: alpine
imageSpec:
  author: "Frontend Maintainer <frontend@example.com>"
  clearHistory: true
  config:
    cmd: ["/usr/bin/start", "--help"]
    entrypoint: ["/bin/sh"]
    env:
      PATH: "/usr/local/bin"
      NODE_ENV: "production"
    expose: ["8080", "443"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: "30s"
      retries: 3
    labels:
      app: "frontend"
      version: "v1"
    stopSignal: "SIGTERM"
    user: "node"
    volumes:
      - "/data"
      - "/config"
    workingDir: "/app"
    removeEnv:
      - "DEBUG"
      - "/^TEMP_.*$/"
    removeLabels:
      - "beta"
      - "/^experimental.*$/"
    removeVolumes:
      - "/tmp"
      - "/var/log"
    keepEssentialWerfLabels: true
    clearCmd: true
    clearEntrypoint: true
    clearUser: true
    clearWorkingDir: true
```
### Things to keep in mind about imageSpec

#### 1. Configuring intermediate images

Global settings don't apply to _intermediate_ images (those marked `final: false`). However, you can still define imageSpec for these images:
```
---
image: api
final: false
imageSpec:
  config:
    removeVolumes:
      - "/tmp"
```

#### 2. Re-using environment variables and limitations

You can only reference environment variables that already exist in the image. Note that variables declared in imageSpec are not available (this behavior corresponds to the Dockerfile's `ENV` instruction):

```
# ✅ Works okay: if PATH is defined in the image, it will be used
imageSpec:
  config:
    env:
      PATH: "${PATH}:/app/bin"
```
```
# ❌ Fails: CUSTOM will be empty as MY_ENV is defined in the same block 
imageSpec:
  config:
    env:
      MY_ENV: MY_VAL
      CUSTOM: "${MY_ENV}"
```

#### 3. Using built-in variables in labels

You can use the built-in `%image%` (image name) and `%project%` (project name) variables when defining labels:

```
project: app
configVersion: 1
build:
  imageSpec:
    config:
      labels:
        app: "%project%"
        image: "%image%"
```

#### 4. Build process impact

Modifying the image configuration does not directly affect the image build process, but allows you to tweak such things as removing unnecessary volumes or adding environment variables for intermediate images:

```
image: base
from: postgres:12.22-bookworm
imageSpec:
  config:
    removeVolumes:
      - "/var/lib/postgresql/data"
---
image: app
fromImage: base
git:
  add: /postgresql/data
  to: /var/lib/postgresql/data
```

#### 5. Some labels cannot be deleted

The werf and `werf.io/parent-stage-id` labels cannot be deleted, as they are vital for cleaning up the host and container registry. To get around this, you can use the `werf export` command, which removes all werf labels by default.


#### 6. Local build considerations

Due to build backend limitations, the use of imageSpec without the `--repo` parameter is not supported. For local builds, you can either ignore the imageSpec stage using the `--skip-image-spec-stage` flag or set up a local container registry via `docker run -d --name=registry --restart=always -p 5000:5000 registry`.

### Additional information

- [OCI Image Format Specification configuration usage documentation](https://werf.io/docs/v2/usage/build/images.html#changing-image-configuration-spec).
- [Complete werf.yaml reference](https://werf.io/docs/v2/reference/werf_yaml.html).
