### DISCUSSION TITLE
werf new feature: External configuration includes (v2.39.0+)

### DISCUSSION THREAD

**Discussion by shurup** [werf/werf#6931] [Announcements]
### Briefly

You can now use any configuration files you need from Git repositories in a centralized and convenient manner.

This is a game-changer if you have **multiple similar applications** and want to **reuse common templates** while keeping them in a separate repository.

_This feature became available starting from werf [v2.39.0](https://github.com/werf/werf/releases/tag/v2.39.0), which is currently in the Alpha release channel._

### Background & details

How it works:
* You define your sources in `werf-includes.yaml`.
* You lock their versions with `werf includes update` or manually by editing `werf-includes.lock`.
* When you run werf, it uses the final (fully merged) configuration.

#### Configuration example

```
# werf-includes.yaml
includes:
  - git: https://github.com/werf/werf
    branch: main
    add: /docs/examples/includes/werf-common
    to: /
    includePaths:
    - .werf

  - git: https://github.com/werf/werf
    branch: main
    add: /docs/examples/includes/common_js
    to: /
    includePaths:
    - .helm
    - .dockerignore
    - *.Dockerfile
```

#### Debugging

We've added a few handy scenarios to make it easier for users to benefit from the new features.

1. List all project files while taking into account all the sources:

```
$ werf includes ls-files

PATH                             SOURCE
.dockerignore                    https://github.com/werf/werf
.helm/templates/deployment.yaml  https://github.com/werf/werf
.helm/templates/service.yaml     https://github.com/werf/werf
.helm/values.yaml                local
.werf/images.tpl                 https://github.com/werf/werf
.werf/cleanup.tpl                https://github.com/werf/werf
.werf/imagespec.tpl              https://github.com/werf/werf
backend.Dockerfile               https://github.com/werf/werf
backend/dummy.ini                local
backend/index.js                 local
backend/package.json             local
frontend.Dockerfile              https://github.com/werf/werf
frontend/index.html              local
werf-includes.lock               local
werf-includes.yaml               local
werf.yaml                        local
```

2. Retrieve the content of a specific file based on the source:

```
$ werf includes get-file .werf/images.tpl

{{- define "image-backend" }}
image: backend
dockerfile: backend.Dockerfile
{{- end }}

{{- define "image-frontend" }}
{{- $backendUrl := default "http://example.org" .backendUrl }}
image: frontend
dockerfile: frontend.Dockerfile
args:
  BACKEND_URL: "{{ $backendUrl }}"
{{- end }}
```

3. Use local repositories:

```
# werf-includes.yaml
includes:
  - git: /path/to/repo
    branch: main
    add: local-dev
    to: /
    includePaths:
      - /.helm
```

#### How does this compare to submodules?

* It is a separate mechanism designed specifically for _configuration_, not _application_ code. This prevents developers from unintentionally pulling in configuration changes when updating submodules.
* It offers more flexible file handling:
  * You can now import arbitrary subsets of files from a source, rather than the entire repository.
  * Per-file overlay rules are supported; directories from sources can overlap with the main project repository.
* It is easier to use. 

#### How does this compare to subcharts?

It complements rather than replaces them! You can import a Helm chart either as a whole or as individual files (e.g., values files, templates, or specific subcharts).

### Additional details

Find more details and scenarios in the documentation:

* [Project configuration / Includes](https://werf.io/docs/v2/usage/project_configuration/includes.html)
