### ISSUE TITLE
[ansible] Become and become user gives MODULE FAILURE

### ISSUE THREAD

**Issue by distorhead** [werf/werf#1806]
```
configVersion: 1
project: testsegfault
---
from: ubuntu:18.04
image: ~
git:
- add: /
  to: /app
ansible:
  install:
  - name: USER
    user:
      name: app
  - name: HELO
    shell: ./main
    args:
      chdir: /app
      executable: /bin/bash
    become: yes
    become_user: app
```

Output:

![image](https://user-images.githubusercontent.com/1161992/66057993-47fee480-e542-11e9-80c9-57cd3a1010de.png)
