### ISSUE TITLE
Support building artifacts from Dockerfile

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2267]
Werf does not allow to define `artifact` image built from `Dockerfile` as follows:

```
artifact: myartifact
dockerfile: ./Dockerfile
```

But importing from image+dockerfile works ok:

```
configVersion: 1
project: alo2
---
image: one
dockerfile: ./Dockerfile
---
image: two
from: alpine
import:
- image: one
  add: /FILE
  to: /MYFILE
  after: install
```
