### ISSUE TITLE
Duplicate key in the values.yaml causes error

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2871]
Werf uses strict yaml loading which could not load following values.yaml:

```
stages:
  prod: &PROD
    test1: 1
    test2: 2

apps:
  app1:
    prod:
      <<: *PROD
      test1: 10
```
