### ISSUE TITLE
werf says build is succesfull, while warning is present

### ISSUE THREAD

**Issue by RomanenkoDenys** [werf/werf#2895]
Build
```
WARNING: Config: {{ .Files.Get 'deckhouse-controller/files/kubectl-wrapper.sh' }}: file '/hom ↵
e/gitlab-runner/builds/2NaTYHyw/0/sys/antiopa/deckhouse-controller/files/kubectl-wrapper.sh'  ↵
not exist!
...
Saving cache
Uploading artifacts for successful job
Job succeeded
```
werf.yaml section with warning
```
  - name: "Install kubectl wrapper"
    copy:
      content: |
{{ .Files.Get "deckhouse-controller/files/kubectl-wrapper.sh" | indent 8 }}
      dest: /usr/local/bin/kubectl
      mode: +x
```
