### ISSUE TITLE
Set --werf-templates-dir and --helm-chart-dir only in werf.yaml

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2897]
Delete cli options, set only in the werf.yaml:

```
project: X
configVersion: 1
config:
  templatesDir: .werf
  helmChartDir: .helm
...
```

Also check that environment param is available in the werf.yaml `--env`.
