### ISSUE TITLE
Add ability to pass secret values into build process in giterminism mode

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2987]
Deploy process supports `.helm/secret-values.yaml` file, which should be committed into the git repo.
Build process may require some secret token, which is typically passed using environment variable.
Currently there is no ability to pass secret token into the build process In the giterminism mode in v1.2.

**Comment by distorhead** [comment]
Fixed by the new werf-giterminism.yaml config: https://github.com/werf/werf/issues/3046

https://werf.io/v1.2-alpha/documentation/advanced/configuration/giterminism.html

For example, define following `werf-giterminism.yaml` config and commit into the git repo of the project:

```
# werf-giterminism.yaml
giterminismConfigVersion: "1"
config:
  goTemplateRendering:
    allowEnvVariables:
      - HELLO
```

Then you can use environment variable named `HELLO` in the `werf.yaml` config:

```
# werf.yaml
...
image: aaa
from: ubuntu:18.04
shell:
  install:
    - echo HELLO={{ env "HELLO" }}
```

**Comment by viperx77** [comment]
If I pass these env vars to my Docker as args, does this mean that everytime the variables change that the images will need to be rebuild or does adding them to allowEnvVariables prevent the diff engine from considering them? Please excuse my lack of understanding as I'm new to werf:

werf.yaml:
```
dockerfile: Dockerfile
args: { CI_JOB_TOKEN: {{ env "CI_JOB_TOKEN" }}, CI_PROJECT_ID: {{ env "CI_PROJECT_ID" }} }

```
werf-giterminism.yaml
```
giterminismConfigVersion: 1
config:
  goTemplateRendering:
    allowEnvVariables:
      - CI_JOB_TOKEN
      - CI_PROJECT_ID
```
