### ISSUE TITLE
Implement fine-grained giterminism config

### ISSUE THREAD

**Issue by distorhead** [werf/werf#3046]
`werf-giterminism.yaml`:

```
giterminismConfigVersion: 1
config: # giterminism configuration for werf.yaml
  allowUncommitted: true
  allowUncommittedTemplates:
    - "**/*"
    - .werf/template.tmpl
  goTemplateRendering:
    allowEnvVariables:                        # {{ env "VARIABLE_X" }}
      - /CI_*/
      - VARIABLE_X
    allowUncommittedFiles:                    # {{ .Files.Get|Glob|... "PATH1" }}
      - "**/*"
      - .werf/nginx.conf
  stapel:
    allowFromLatest: true
    git:
      allowBranch: true
    mount:
      allowBuildDir: true                     # from: build_dir
      allowFromPaths:                         # fromPath: PATH
        - PATH1
        - PATH2
  dockerfile:
    allowUncommitted:
      - "**/*"
      - myapp/Dockerfile
    allowUncommittedDockerignoreFiles:
      - "**/*"
      - myapp/.dockerignore
    allowContextAddFiles:
      - aaa
      - bbb
helm: # giterminism configuration for helm
  allowUncommittedFiles:
    - "templates/**/*"
    - values.yaml
    - Chart.yaml
```

- [x] config.allowUncommitted
- [x] config.allowUncommittedTemplates
- [x] config.goTemplateRendering.allowEnvVariables
- [x] config.goTemplateRendering.allowUncommittedFiles
- [x] config.stapel.allowFromLatest
- [x] config.stapel.git.allowBranch
- [x] config.stapel.mount.allowBuildDir
- [x] config.stapel.mount.allowFromPaths
- [x] config.dockerfile.allowUncommitted
- [x] config.dockerfile.allowUncommittedDockerignoreFiles
- [x] config.dockerfile.allowContextAddFiles
- [ ] helm.allowUncommittedFiles
