### ISSUE TITLE
Forward values with werf image path to subcharts

### ISSUE THREAD

**Issue by tuchinsky** [werf/werf#3411]
Use custom parameters in dependencies list in parent `Chart.yaml` for forward value with image path to subchart

For example:
```
apiVersion: v2
name: parentChart
version: 1.0.0
dependencies:
- name: subChart
  version: 1.0.0
  repository: https://charts.flant.com
  condition: subchart.enabled
  alias: subchart
  werfAllowImages:
  - frontend
  - backend
```

in subchart value with image path can be `.Values.global.werf.image.frontend` or `.Values.subchart.werf.image.frontend`
