### ISSUE TITLE
Unexpected behaviour of custom annotations when adopting resources into the helm 3 release

### ISSUE THREAD

**Issue by distorhead** [werf/werf#3422]
After converge helm release contains rendered custom annotations:

```
# Source: k8s-infra/templates/DexProvider.yaml
apiVersion: deckhouse.io/v1alpha1
kind: DexProvider
metadata:
  annotations:
    ci.werf.io/commit: COMMIT
    github.ci.werf.io/workflow-run-url: URL
    project.werf.io/env: prod
    project.werf.io/git: URL
    project.werf.io/name: k8s-infra
    werf.io/version: v1.2.9+fix10
  name: github
```

But resource does not contain any.

After several retries some annotations appeared, but not all needed annotations:

```
apiVersion: deckhouse.io/v1alpha1
kind: DexProvider
metadata:
  annotations:
    ci.werf.io/commit: COMMIT
    github.ci.werf.io/workflow-run-url: URL
    meta.helm.sh/release-name: k8s-infra
    meta.helm.sh/release-namespace: default
```
