### ISSUE TITLE
werf deploy is finished before the resources start

### ISSUE THREAD

**Issue by sasokol** [werf/werf#3506]

**Comment by distorhead** [comment]
Some info:

```
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: myapp
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
```

Need a way to reproduce.
