### ISSUE TITLE
Helm Repositories in Github Actions

### ISSUE THREAD

**Issue by deen13** [werf/werf#3596]
Hey, 

my current project requires some helm charts that are defined in the `chart.yaml`. 

```yaml
# .helm/Chart.yaml
apiVersion: v2
name: myproject
version: 1.0.0
dependencies:
  - name: traefik
    version: "9.17.5"
    repository: "https://helm.traefik.io/traefik"
  - name: keycloak
    version: "11.0.0"
    repository: "https://codecentric.github.io/helm-charts"
  - name: cert-manager
    version: "v1.3.1"
    repository: "https://charts.jetstack.io"
```

In order to deploy the application with the given helm dependencies I need to setup all required repositories. 

```
      - name: Setup Traefik Repository
        run: helm repo add traefik https://helm.traefik.io/traefik

      - name: Setup Codecentric Repository
        run: helm repo add codecentric https://codecentric.github.io/helm-charts

      - name: Setup Jetstack Repository
        run: helm repo add jetstack https://charts.jetstack.io
```

It would be great to automate this because every time a developer adds a new helm dependency its likely that he breaks the build and adds the repository setup afterwards.
