### ISSUE TITLE
Add ability to autoupdate patch versions of dependencies charts

### ISSUE THREAD

**Issue by distorhead** [werf/werf#3767]
Need a special format for Chart.lock, that only fixates major and minor versions of the chart. `werf helm dependency build` then  should auto update patch versions of such dependencies.

**Comment by ilya-lesikov** [comment]
This can be done with
```yaml
# .helm/Chart.yaml
dependencies:
- name: ...
  version: "~1.0"
```
and manually running `werf helm dependency update` before deploy, although by default this is disallowed by giterminism.

It is unclear what can be improved, needs research.
