### ISSUE TITLE
Add after patch stage

### ISSUE THREAD

**Issue by konstantin-axenov** [werf/werf#384]
При сборке некоторых приложений необходимо запускать набор команд в случае обновления исходников. Сейчас данный вопрос решается добавлением следующей директивы в git артифакт

`stage_dependencies.setup '**/*'`

Необходимо добавить стадию after.patch для git артифакта, которая будет выполняться, в случае, если применялся патч

**Comment by alexey-igrychev** [comment]
как workaround сейчас можно использовать следующий подход:
```
dimg: from
from: alpine
git:
- add: /
  to: /app
---
dimg: app
fromDimg: from
shell:
  setup: command
```
