### ISSUE TITLE
Add warning when .helm folder being added into the image or autoexclude

### ISSUE THREAD

**Issue by distorhead** [werf/werf#3910]
```
git:
- add: /
  to: /app
```

should be changed to

```
git:
- add: /
  to: /app
  excludePaths:
  - .helm/
```

to disable warning.

The better approach would be to auto exclude `.helm` always, unless explicitly added.
