### ISSUE TITLE
{} are not properly interpreted in `--set-(string)` value

### ISSUE THREAD

**Issue by ilya-lesikov** [werf/werf#3924]
Prerequisites:
```yaml
# werf.yaml
project: projname99
configVersion: 1
```
```yaml
# .helm/templates/test.yaml
out: | {{ $.Values | toYaml | nindent 2 }}
```

Commands:
```shell
werf render --set 'key={value}'
werf render --set-string 'key={value}'
```
Result in:
```yaml
...
key:
  - value
...
```
Expected instead:
```yaml
...
key: '{value}'
...
```

werf v1.2.37+fix1
