### ISSUE TITLE
Dockerfile checksum CLI command

### ISSUE THREAD

**Issue by alexbechmann** [werf/werf#4060]
Would it be possible to add a CLI command to output the checksum?

# Given the config file
```yaml
project: my-project
configVersion: 1
---
image: api
dockerfile: api.Dockerfile
context: apps
---
image: frontend
dockerfile: frontend.Dockerfile
context: apps

```

# Where
```bash
werf build api
```
produces image: `my-project:123CHECKSUM321-TIMESTAMP` - with the checksum calculated from Dockerfile+src files

# Desired
I would like a command that can return the checksum `123CHECKSUM321` as a string

```bash
werf checksum api
123CHECKSUM321
```
