### ISSUE TITLE
Commit info (hash, data) are natively available during deploy and build

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#4122]
### 1. Assembly instructions usage (will not trigger rebuilds):
```yaml
# werf.yaml:
shell:
  install:
  - echo $WERF_COMMIT_DATE_UNIX
  - echo $WERF_COMMIT_DATE_HUMAN
  - echo $WERF_COMMIT_HASH 
```
These variables automatically exported into the build container, which makes them available to shell.

### 2. werf.yaml templates usage (**will trigger rebuilds**):
```yaml
from: ubuntu:20.04
fromCacheVersion: {{ div .Commit.Date.Unix (mul 60 60 24 30) }}
```
Useful for determined rebuilds of whole images (`fromCacheVersion`) or only specific stages (`...CacheVersion`).

### 3. Helm templates usage:
```yaml
# .helm/templates/test.yaml:
  annotations:
    commit-date-unix: "{{ $.Values.werf.commit.date.unix }}"
    commit-date: "{{ $.Values.werf.commit.date.human }}"
    commit: "{{ $.Values.werf.commit.hash }}"
...
          env:
          - name: COMMIT
            value: "{{ $.Values.werf.commit.hash }}"
```

_Originally posted by @ilya-lesikov in https://github.com/werf/werf/issues/54#issuecomment-1023063456_
