### ISSUE TITLE
Implement dependencies between images

### ISSUE THREAD

**Issue by distorhead** [werf/werf#4124]
1. We need a way to define dependencies between images, so that dependant images will be built only when its dependencies are built.
2. We need a way to get image name and ID of each image dependency when building current image.
3. Images dependencies could use any builder type: dockerfile or stapel.

## Syntax

Dependencies for image built with dockerfile builder:

```
# werf.yaml
image: x
dockerfile: ./Dockerfile
dependencies:
- image: NAME
  imports: # optional
  - type: {ImageName|ImageID|ImageRepo|ImageTag}
    targetBuildArg: BUILD_ARG_NAME
```

Dependencies for image built with stapel builder:

```
# werf.yaml
image: y
from: alpine
shell:
  install:
  - INSTRUCTION
dependnecies:
- image: NAME
  {before|after}: {install|setup}
  imports: # optional
  - type: {ImageName|ImageID|ImageRepo|ImageTag}
    targetEnv: ENV_VAR_NAME
```

## How it works

* To build current image werf first need to build each dependency image (and it's dependencies in turn).
* `imports` directive is optional and enable user to access info about dependency image, such as full image name, id, repo or tag.
* Depending of current image builder type (dockerfile or stapel) werf could export dependency image info using:
    * build-args for dockerfile image;
    * environment variables for stapel image.
* Stapel builder requries `{before|after}: {install|setup}` directive.
    * Specified in the imports target environment variables for each dependency will be available either on `install`, `beforeSetup` or `setup` stage.

### Use stapel image as base in Dockerfile image

```
# werf.yaml
image: x
from: alpine
shell:
  install:
  - echo "This is stapel image"
  - apk add bash git
---
image: y
dockerfile: ./Dockerfile
dependencies:
- image: x
  imports:
  - type: ImageName
    targetBuildArg: BASE_IMAGE
```

```
# Dockerfile
ARG BASE_IMAGE=alpine:latest

FROM ${BASE_IMAGE}
RUN git status
```

### Multistage between multiple Dockerfiles

```
# werf.yaml
image: x
dockerfile: Dockerfile.x
---
image: y
dockerfile: Dockerfile.y
---
image: z
dockerfile: Dockerfile.z
dependencies:
- image: x
  imports:
  - type: ImageName
    targetBuildArg: X_IMAGE_NAME
- image: y
  imports:
  - type: ImageName
    targetBuildArg: Y_IMAGE_NAME
```

```
# Dockerfile.z

FROM alpine

ARG X_IMAGE_NAME
ARG Y_IMAGE_NAME

RUN echo ${X_IMAGE_NAME} >> images-list.txt
RUN echo ${Y_IMAGE_NAME} >> images-list.txt
```

**NOTE** Specified build-args are available not only in the meta section of the Dockerfile, but in any place of the Dockerfile as regular user build-args.

### Link to dependencies images in the dependant images in build time

```
# werf.yaml
image: module-one
from: alpine
...
---
image: module-two
from: centos
...
---
image: module-three
from: ubuntu
...
---
image: main
from: alpine
dependencies:
- image: module-one
  before: install
  imports:
  - type: ImageName
    targetEnv: MODULE_ONE_IMAGE_NAME
- image: module-two
  before: install
  imports:
  - type: ImageName
    targetEnv: MODULE_ONE_IMAGE_NAME
- image: module-three
  before: install
  imports:
  - type: ImageName
    targetEnv: MODULE_ONE_IMAGE_NAME
shell:
  install:
  - echo $MODULE_ONE_IMAGE_NAME >> modules-images.txt
  - echo $MODULE_TWO_IMAGE_NAME >> modules-images.txt
  - echo $MODULE_THREE_IMAGE_NAME >> modules-images.txt
```
