### ISSUE TITLE
bug(imports): import[].includePaths includes more than required

### ISSUE THREAD

**Issue by ilya-lesikov** [werf/werf#4176]
Given:
```yaml
# werf.yaml:
project: none
configVersion: 1
---
image: image1
from: alpine
shell:
  install:
  - mkdir -p /src/app/nested
  - touch /src/app/test1 /src/app/test2.jar /src/app/nested/test3 /src/app/nested/test4.jar
---
image: image2
from: alpine
import:
- image: image1
  add: /src/app
  to: /app
  before: install
  includePaths:
  - '**/*.jar'
shell:
  install:
  - echo
```

Executing `werf run image2 -- find /app` shows:
```yaml
/app
/app/test2.jar
/app/nested
/app/nested/test3
/app/nested/test4.jar
/app/test1
```

But expecting:
```yaml
/app/nested/test4.jar
```

Internal generated rsync command which is used to copy files:
```shell
RSYNC_PASSWORD='xxx' /.werf/stapel/embedded/bin/rsync --archive --links --inplace  --filter='+/ /src/app/**/*.jar' --filter='+/ /src/app/**' --filter='+/ /src/app' --filter='+/ /src' --filter='+/ /src/app/**/*.jar' --filter='+/ /src/app/**/*.jar/**' --filter='-/ /src/app/**' rsync://werf-1125f69a@172.17.0.4:873/import//src/app$IMPORT_PATH_TRAILING_SLASH_OPTIONAL /app
```
