### ISSUE TITLE
Validate invalid non-string annotations and labels

### ISSUE THREAD

**Issue by distorhead** [werf/werf#4282]
For example:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    hello: world
    test: false
```

will result in no annotations added to the Deployment. The next configuration will work though:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    hello: world
    test: "false"
```
— this uses string value `"false"` instead of boolean.

Expected werf to validate such invalid annotations in the .helm/templates somehow. If possible in the `werf render` command, or using server dry-run.
