### ISSUE TITLE
bundles: auto-vendor all dependencies into published bundle

### ISSUE THREAD

**Issue by distorhead** [werf/werf#4581]
Suppose we have following dependencies:

```
# .helm/Chart.yaml
apiVersion: v2
dependencies:
- name: redis
  version: "16.0.0"
  repository: "https://charts.bitnami.com/bitnami"
- name: redis2
  version: "16.0.0"
  repository: "file://../vendor_charts/redis2"
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
```

1. Automatically download all dependencies and store into the bundle during `werf bundle publish`.
2. Support relative paths in repository like `file://../vendor_charts/redis2`. Such chart located outside of `.helm`, but should be saved into the bundle.
