### ISSUE TITLE
Different behaviour of werf render with and without --repo when no environment used

### ISSUE THREAD

**Issue by distorhead** [werf/werf#4659]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

1.2.138

### How to reproduce

Use `.Values.werf.env` in helm templates like follows:

```
# .helm/templates/template.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    hello:  {{ pluck .Values.werf.env .Values.db.url | first | default .Values.db.url._default | quote }}
...
```

Run `werf render` with, without `--repo` param.

### Result

WIth `--repo` param render will fail like follows:

```
$ werf render --repo ghcr.io/distorhead/quickstart-application
Error: helm templates rendering failed: 
  template: quickstart-application/templates/001-vote.yaml:6:28: executing "quickstart-application/templates/001-vote.yaml" at <.Values.werf.env>: wrong type for value; expected string; got interface {}

Use --debug flag to render out invalid YAML
```

Wihtout `--repo` param render will succeed.

### Expected result

Expected the same behaviour of render with and without `--repo` param. 

### Additional information

The reason of different behaviour is because werf render insert empty stub value `.Values.werf.env=""` when no `--repo` specified, and insert no value (null) otherwise.

`werf converge` command also inserts null value.

Solution: always insert empty `.Values.werf.env=""` in render with `--repo` and converge commands (only if this does not break backward compatibility).
