### ISSUE TITLE
Default global user for images building and runtime

### ISSUE THREAD

**Issue by distorhead** [werf/werf#4713]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

It is error-prone and needs a lot of instructions to setup and prepare images using instructions run by non-root user and use non-root user when running image.

### Solution (if you have one)

Define user to be used globally for image build instructions and runtime:
1. Import artifacts
2. Git-add instructions.
3. Shell-instructions.
4. Docker-instructions for image runtime.

For example:

```
# werf.yaml
---
image: x
user: non-root-user
shell:
  install:
  - touch /app/file # will be owned by non-root-user
git:
- add: /
  to: /app # will be owned by non-root-user
import:
- image: other
  add: /out
  to: /app/out # will be owned by non-root-user
  after: install
```
