### ISSUE TITLE
werf converge do not install chart dependencies

### ISSUE THREAD

**Issue by abrekhov** [werf/werf#4761]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

latest

### How to reproduce

https://werf.io/documentation/v1.2/advanced/helm/configuration/chart_dependencies.html

I am using werf container with kubernetes executor in Gitlab CI. 

My `.helm/Chart.yaml`

```yaml
apiVersion: "v2"
name: appofapp
version: "0.0.1"
dependencies:
  - name: gitlab-runner
    version: "0.43.1"
    repository: "http://charts.gitlab.io/"
``` 

My `.gitlab-ci.yml`

```yaml
stages:
  - converge
converge:
  stage: converge
  tags: ["werf"]
  image: registry.werf.io/werf/werf
  script:
  - source $(werf ci-env gitlab --as-file)
  - werf converge
```

My generated `.helm/Chart.lock` : 

```yaml
dependencies:
- name: gitlab-runner
  repository: http://charts.gitlab.io/
  version: 0.43.1
digest: sha256:9de602aa17f42f97a0759f7dc538dedcc8baaf8d337309139dfbd5897165768c
generated: "2022-08-12T11:43:38.648382+03:00"
```

### Result

Error: helm upgrade have failed: unable to load files from dir /builds/mks/crossplane/.helm: chart dependencies loader failed: error preparing chart dependencies: error building chart dependencies: no repository definition for http://charts.gitlab.io/. Please add the missing repos via 'helm repo add'

### Expected result

As said [here](https://werf.io/documentation/v1.2/advanced/helm/configuration/chart_dependencies.html) : 

> Later during deploy process (with [werf converge command](https://werf.io/documentation/v1.2/reference/cli/werf_converge.html) or [werf bundle apply command](https://werf.io/documentation/v1.2/reference/cli/werf_bundle_apply.html)), or during templates rendering (with [werf render command](https://werf.io/documentation/v1.2/reference/cli/werf_render.html)) werf will automatically download all dependencies specified in the lock file .helm/Chart.lock.
