### ISSUE TITLE
InvalidImageName after deploying to kubernetes cluster with image "map[bar:registry.example.com/foo/bar:tag]"

### ISSUE THREAD

**Issue by dimasadriansyah** [werf/werf#4763]
### Information

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

```werf.yaml```
```
configVersion: 1
project: bar
---
image: bar
dockerfile: Dockerfile
context: .
```

```deployment.yaml```
```
---
spec:
  containers:
   - name: bar
      image: {{ .Values.werf.image }}
```
and then i run using command ```werf converge --repo registry.example.com/foo/bar```

### Version

latest

### Result

InvalidImageName when deploying to kubernetes cluster

### Expected result

can using valid image name
