### ISSUE TITLE
Explicitly specified empty annotations in resource manifest result in no service annotations on deployed resource

### ISSUE THREAD

**Issue by ilya-lesikov** [werf/werf#4933]
The user reports that this manifest:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  name: "migrations-20220901103747"
```
...results in no Helm/werf annotations on the deployed Job resource, thus werf will not delete it when the resource is removed from the release.

**Comment by ilya-lesikov** [comment]
Partially reproduced. Some annotations are missing, but not all, and this is enough to clean up the resource that is no longer in release.

Expected annotations:
```yaml
    annotations:
      meta.helm.sh/release-name: none
      meta.helm.sh/release-namespace: none
      project.werf.io/env: ""
      project.werf.io/name: none
      werf.io/version: v1.2.172
```

Actual annotations:
```yaml
    annotations:
      meta.helm.sh/release-name: none
      meta.helm.sh/release-namespace: none
```

We should always apply all service annotations.
