### ISSUE TITLE
Error: UPGRADE FAILED: error applying resources: ... already exists

### ISSUE THREAD

**Issue by distorhead** [werf/werf#4965]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

v1.2.163+fix1, v1.2.174

### How to reproduce

Problematic resource:
```
apiVersion: deckhouse.io/v1
kind: AWSInstanceClass
metadata:
  annotations:
    meta.helm.sh/release-name: cluster
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  name: system
spec:
  diskSizeGb: 50
  diskType: gp3
  instanceType: t3a.large
```

Non-problematic resource:
```
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  annotations:
    meta.helm.sh/release-name: cluster
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  name: system
spec:
  cloudInstances:
    classReference:
      kind: AWSInstanceClass
      name: system
    maxPerZone: 2
    minPerZone: 2
    zones:
    - eu-central-1a
  nodeTemplate:
    labels:
      node-role.deckhouse.io/system: ""
    taints:
    - effect: NoExecute
      key: dedicated.deckhouse.io
      value: system
  nodeType: CloudEphemeral
```

### Result

```
Error: helm upgrade have failed: UPGRADE FAILED: error processing rollout phase stage: error applying resources: [awsinstanceclasses.deckhouse.io](http://awsinstanceclasses.deckhouse.io/) "frontend" already exists
```

### Expected result

No errors.
