### ISSUE TITLE
Cannot build image when using kubernetes synchronization

### ISSUE THREAD

**Issue by abrekhov** [werf/werf#4987]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

v1.2.169+fix1

### How to reproduce

1. Use GitlabCI
2. Use [werf inside gitlab-runner container](https://werf.io/documentation/v1.2/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_kubernetes_executor.html)
3. Try to just build the image on non default and non protected branch.
4. Part of `gitlab-ci.yml`
```yaml

build_image:
  stage: build_image
  image: registry.werf.io/werf/werf
  variables:
    WERF_ENV: staging
    WERF_SYNCHRONIZATION: kubernetes://gitlab-ci
  script:
    - source $(werf ci-env gitlab --as-file)
    - export
    - werf build --repo $WERF_REPO
  tags: ["werf-staging"]
  rules:
    - if: $CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH != "main"
```

### Result

```bash
$ werf build --repo $WERF_REPO
Version: v1.2.169+fix1
Using project dir: /builds/platform/esports
Using werf config render file: /tmp/werf-config-render-3649963931
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2901dbf]
goroutine 1 [running]:
github.com/werf/werf/cmd/werf/common.GetSynchronization.func1({0xc000058075, 0x16}, 0x0)
	/git/cmd/werf/common/synchronization.go:118 +0xbf
github.com/werf/werf/cmd/werf/common.GetSynchronization({0x3ccb700?, 0xc0003253b0?}, 0x57f7de0, {0xc0011a8020?, 0x57f7de0?}, {0x7f94866b7f20, 0xc00082c5a0})
	/git/cmd/werf/common/synchronization.go:162 +0x295
github.com/werf/werf/cmd/werf/build.run({0x3ccb700, 0xc0003253b0}, {0x3ce0898, 0xc000ab1be0}, {0x3cd6480, 0xc000d5f2f0?}, {0xc0004656a0, 0x0, 0x2})
	/git/cmd/werf/build/main.go:224 +0x349
github.com/werf/werf/cmd/werf/build.runMain({0x3ccb700, 0xc0003253b0}, {0xc0004656a0?, 0x0, 0x2})
	/git/cmd/werf/build/main.go:193 +0x692
github.com/werf/werf/cmd/werf/build.NewCmd.func1.1()
	/git/cmd/werf/build/main.go:66 +0x2d
github.com/werf/werf/cmd/werf/common.LogRunningTime(0xc00121fcc8)
	/git/cmd/werf/common/common.go:1225 +0x42
github.com/werf/werf/cmd/werf/build.NewCmd.func1(0xc000470c80, {0xc0004656a0, 0x0, 0x2})
	/git/cmd/werf/build/main.go:65 +0x1b5
main.setupTelemetryInit.func1(0xc000470c80?, {0xc0004656a0, 0x0, 0x2})
	/git/cmd/werf/main.go:287 +0xd2
github.com/spf13/cobra.(*Command).execute(0xc000470c80, {0xc000465680, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a43b80)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/git/cmd/werf/main.go:79 +0x139

```

### Expected result

Successful build
