### ISSUE TITLE
Install elasticsearch with werf failed, without werf ok

### ISSUE THREAD

**Issue by patsevanton** [werf/werf#4998]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

1.2.177

### How to reproduce
```
helm repo add bitnami https://charts.bitnami.com/bitnami

werf helm install --atomic -n elasticsearch my-elasticsearch bitnami/elasticsearch --version 19.4.2  -f value.yaml
```

value.yaml
```
master:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 256Mi

data:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 256Mi

coordinating:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 256Mi

metrics:
  enabled: true
```

### Result

log werf by install elasticsearch

https://gist.github.com/patsevanton/663027a4040057011f743f3142d039f3

### Expected result

Install elasticsearch with werf passed

### Additional information

install without werf
```
helm install --atomic -n elasticsearch my-elasticsearch bitnami/elasticsearch --version 19.4.2  -f value.yaml 
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/user/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/user/.kube/config
NAME: my-elasticsearch
LAST DEPLOYED: Tue Oct 11 21:10:11 2022
NAMESPACE: elasticsearch
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: elasticsearch
CHART VERSION: 19.4.2
APP VERSION: 8.4.2

-------------------------------------------------------------------------------
 WARNING

    Elasticsearch requires some changes in the kernel of the host machine to
    work as expected. If those values are not set in the underlying operating
    system, the ES containers fail to boot with ERROR messages.

    More information about these requirements can be found in the links below:

      https://www.elastic.co/guide/en/elasticsearch/reference/current/file-descriptors.html
      https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

    This chart uses a privileged initContainer to change those settings in the Kernel
    by running: sysctl -w vm.max_map_count=262144 && sysctl -w fs.file-max=65536

** Please be patient while the chart is being deployed **

  Elasticsearch can be accessed within the cluster on port 9200 at my-elasticsearch.elasticsearch.svc.cluster.local

  To access from outside the cluster execute the following commands:

    kubectl port-forward --namespace elasticsearch svc/my-elasticsearch 9200:9200 &
    curl http://127.0.0.1:9200/
```

get pod
```
kubectl get pod -n elasticsearch
NAME                                       READY   STATUS    RESTARTS   AGE
my-elasticsearch-coordinating-0            1/1     Running   0          3m39s
my-elasticsearch-data-0                    1/1     Running   0          3m39s
my-elasticsearch-ingest-0                  1/1     Running   0          3m39s
my-elasticsearch-ingest-1                  1/1     Running   0          3m39s
my-elasticsearch-master-0                  1/1     Running   0          3m39s
my-elasticsearch-metrics-944c9685b-8w486   1/1     Running   0          3m39s
```

Full log elasticsearch install by helm
https://gist.github.com/patsevanton/32619ebad0087372842f6999c2e03817
