### ISSUE TITLE
Render of multiline string breaks pretty yaml printing in certain cases

### ISSUE THREAD

**Issue by distorhead** [werf/werf#5343]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

1.2.204

### How to reproduce

Define a manifest with string-value as multiline yaml which contains empty string with number of spaces more than identation level:

```yaml
---$
apiVersion: v1$
kind: ConfigMap$
metadata:$
  name: cm$
data:$
  stringkey: |$
    hello: world$
     $
    test: value$
```

Note that after `hello: world` there is 5 spaces, while identation of string value yaml is 4 spaces.

### Result

Run `werf render` (or `werf helm template .helm`):

```yaml
# Source: test/templates/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  annotations:
    project.werf.io/env: ""
    project.werf.io/name: x
    werf.io/version: dev
data:
  stringkey: "hello: world\n \ntest: value\n"
```

`stringkey` value is no more multiline string.

### Expected result

Running vanilla `helm template .helm` does not break multiline representation of `stringkey`:

```yaml
---
# Source: test/templates/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
data:
  stringkey: |
    hello: world
     
    test: value
```
