### ISSUE TITLE
How to get git info in the build container

### ISSUE THREAD

**Issue by distorhead** [werf/werf#54]
As a developer of an application, which built by the werf, I want to have ability to get application version — git commit, tag or other info — to embed this info into final application image.

Maybe all CI-variables should be forwarded into build container.

**Comment by distorhead** [comment]
В качестве выполнения этого issue: написать статью о том, как сделать это с помощью артефакта.

**Comment by alexey-igrychev** [comment]
```
dimg: ~
from: alpine
import:
- artifact: "app version"
  after: setup
  add: /version
---
artifact: "app version"
from: alpine
ansible:
  buildArtifact:
  - copy:
      dest: /version
      content: |
        {{ env "CI_COMMIT_REF_NAME" }}-{{ env "CI_COMMIT_SHA" }}
```

**Comment by distorhead** [comment]
The variant with an artifact will cause application rebuild on each commit. And when commits do not contain any changes to the image content — this application rebuild is not a desireable behaviour.

**Comment by distorhead** [comment]
Info from dup issue https://github.com/flant/werf/issues/2217

What about mounting dot-git of the main repo into build container?

```
fromPath: .git
to: /app/.git
```

But mounting is always a bad decision because it does not scale well.

There should be more cases of .git usage, which should be documented in this issue.

### Ideas and info

 - Export environment variables with git commit sha for local and all remote git mappings.
 - What about commits in submodules?
 - In some projects `git describe --tags --always` is used to get version info of current repo and submodules.

**Comment by distorhead** [comment]
If build instructions need to access git-info, but it is unnecessary to rebuild image when this git-info changed, then there is a way using mounts.

 1. Generate gitInfo.sh file in the root of the project before werf build call:
```
echo export CI_COMMIT_SHA=$CI_COMMIT_SHA >> gitInfo.sh
```
 2. Mount this file using `mount.fromPath`:
```
mount:
- fromPath: gitInfo.sh
  to: /.werf/gitInfo.sh
```
 3. Source gitInfo in build instructions:
```
shell:
  install:
  - source /.werf/gitInfo.sh
  - echo $CI_COMMIT_SHA
```

**Comment by ilya-lesikov** [comment]
## **Commit info (hash, data) are natively available during deploy and build in v1.2.58+**

### 1. Assembly instructions usage (will not trigger rebuilds):
```yaml
# werf.yaml:
shell:
  install:
  - echo $WERF_COMMIT_DATE_UNIX
  - echo $WERF_COMMIT_DATE_HUMAN
  - echo $WERF_COMMIT_HASH 
```
These variables automatically exported into the build container, which makes them available to shell.

### 2. werf.yaml templates usage (**will trigger rebuilds**):
```yaml
from: ubuntu:20.04
fromCacheVersion: {{ div .Commit.Date.Unix (mul 60 60 24 30) }}
```
Useful for determined rebuilds of whole images (`fromCacheVersion`) or only specific stages (`...CacheVersion`).

### 3. Helm templates usage:
```yaml
# .helm/templates/test.yaml:
  annotations:
    commit-date-unix: "{{ $.Values.werf.commit.date.unix }}"
    commit-date: "{{ $.Values.werf.commit.date.human }}"
    commit: "{{ $.Values.werf.commit.hash }}"
...
          env:
          - name: COMMIT
            value: "{{ $.Values.werf.commit.hash }}"
```
