### ISSUE TITLE
Can't base the image on 'scratch' in stapel

### ISSUE THREAD

**Issue by DCNick3** [werf/werf#5472]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

v1.2.198

### How to reproduce

Make a `werf.yaml` image/artifact depending on `scratch` docker pseudo-image.

For example:

```yaml
configVersion: 1
project: scratch-testing
---
image: scratch-testing
from: scratch
shell:
  install:
    # download a binary for cargo-chef
    - wget https://github.com/LukeMathWalker/cargo-chef/releases/download/v0.1.52/cargo-chef-x86_64-unknown-linux-musl.tar.gz -O - | tar -xz
    - mv cargo-chef /usr/local/bin
```

Now try to build it with `werf build`

### Result

An error message:

```
Version: v1.2.198
Using werf config render file: /tmp/werf-config-render-3714473006

┌ ⛵ image scratch-testing
└ ⛵ image scratch-testing (2.63 seconds) FAILED

Running time 2.65 seconds
Error: phase build before image scratch-testing stages handler failed: unable to setup base image: unable to get base image "scratch" manifest: reading image "scratch": GET https://index.docker.io/v2/library/scratch/manifests/latest: MANIFEST_UNKNOWN: manifest unknown; unknown tag=latest
```

### Expected result

A docker image containing only `cargo-chef` is created

### Additional information

This is somewhat similar to #2777, but in stapel instead of `Dockerfile` now
