### ISSUE TITLE
werf helm dependency update not using values at WERF_VALUES_1

### ISSUE THREAD

**Issue by Ixorasoft** [werf/werf#5854]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

1.2.248

### How to reproduce

**gitlab-ci.yaml**
```
gitlab-ci-job:
  stage: deploy
  tags: [k8s-main]
  image: registry.werf.io/werf/werf
  variables:
    WERF_SYNCHRONIZATION: kubernetes://gitlab-ci
    WERF_CONFIG: my-folder/werf.yml 
    WERF_VALUES_1: my-folder/my-values-1.yml
    WERF_VALUES_2: my-folder/my-values-2.yml

  script:
    - source "$(werf ci-env gitlab --as-file)"
    - werf version
    - werf helm dependency update ${CI_PROJECT_DIR}/my-helm/.helm
    - cd ${CI_PROJECT_DIR}
    - git config --global user.email "werf@werf.ru"
    - git config --global user.name "GitLab Runner ${CI_RUNNER_ID}"
    - git add --all
    - git commit -m "download chart dependences" 
    - werf converge
  environment:
    name: dev
```

file **my-helm/Chart.yaml** 
```
apiVersion: v2
name: my-chart-name
type: application
appVersion: 0.0.0
version: "1.0.0"
dependencies:
  - name: postgresql # имя строго как в каталоге производителя чарта
    repository: https://charts.bitnami.com/bitnami
    version: 13.2.0 # chart version!!!  Chart v13.2.0 -> postgres sql 16.0.0
    alias: postgresql-16-0-0
    condition: stend.cluster.infrastructure.postgresql-16-0-0.enabled
```

file **my-folder/my-values-2.yml**
```
stend:
  cluster: 
    infrastructure:       
      postgresql-16-0-0: 
        enabled: false
```

### Result

Result
```
Running with gitlab-runner 16.1.0 (b72e108d)
  on gitlab-runner-6c8bcb487-ds4xn 
Preparing the "kubernetes" executor

Using Kubernetes namespace: gitlab-ci
Using Kubernetes executor with image registry.werf.io/werf/werf ...
Using attach strategy to execute scripts...
Preparing environment
Waiting for pod gitlab-ci/runner-qytay21ha-project-78-concurrent-0gbflr to be running, status is Pending
Running on runner-qytay21ha-project-78-concurrent-0gbflr via gitlab-runner-6c8bcb487-ds4xn...
Getting source from Git repository
Fetching changes with git depth set to XXX
Initialized empty Git repository in /builds/12
Created fresh repository.
Checking out b9d094c4 as detached HEAD ...
Skipping Git submodules setup
Executing "step_script" stage of the job script
$ source "$(werf ci-env gitlab --as-file)"
$ werf version
v1.2.
$ werf helm dependency update ${CI_PROJECT_DIR}/my-helm/.helm
**Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
Saving 4 charts
Downloading postgresql from repo https://charts.bitnami.com/bitnami
Deleting outdated charts**
....
```

### Expected result

$ werf helm dependency update ${CI_PROJECT_DIR}/my-helm/.helm

NOTHING!!!
because :
- stend.cluster.infrastructure.postgresql-16-0-0.enabled: false  in file my-folder/my-values-2.yml 
- env WERF_VALUES_2=my-folder/my-values-2.yml
