### ISSUE TITLE
deepCopy in werf.yaml not working

### ISSUE THREAD

**Issue by Ixorasoft** [werf/werf#5860]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

1.2.248

### How to reproduce

solution.yml
```
solution:
  name: sample

  defaultValues:
    microservises:
      containerPort: 8000
      stagedImageBuild: false
      dockerfile: .deploy/Dockerfile
  microservises:
    - name: helloworld
      path: Services/Samples/HelloWorld #without ending /
      dockerfile: .deploy/Dockerfile
```
werf,yaml
```
{{- $solutionYaml := print "solutions/" $solutionName "/" $solutionName ".yml" | .Files.Get | fromYaml -}}
{{- $solution := $solutionYaml.solution  -}}
configVersion: 1
project: {{ $solution.name }}

{{- range $ms := $solution.microservises}}
{{- $testValue := $solution.defaultValues.microservises }}
{{- $msWithDefaults := mergeOverwrite  (deepCopy $solution.defaultValues.microservises) (deepCopy $ms) }}   
---
image: {{ $ms.name }}
context: {{ $ms.path }}
dockerfile: {{ $ms.dockerfile }}
{{- end }}
```

### Result

$ werf converge
```
Version: v1.2.248
Using project dir: /builds/13057/ixora-platform
Running time 0.27 seconds
Error: unable to load werf config: template: werfConfig:37:69: executing "werfConfig" at <$solutionYaml.solution.defaultValues.microservises>: wrong type for value; expected map[string]interface {}; got map[interface {}]interface {}
Cleaning up project directory and file based variables
ERROR: Job failed: command terminated with exit code 1
```
Error in line:
`{{- $msWithDefaults := mergeOverwrite  (deepCopy $solution.defaultValues.microservises) (deepCopy $ms) }}   `

### Expected result

without error

### Additional information

gitlab-ci.yaml
```
k8s-main-werf:
  stage: k8s-main-werf
  tags: [k8s-main]
  image: registry.werf.io/werf/werf
  variables:
    IXORA_CICD_SOLUTION: ${SOLUTION}
    IXORA_CICD_STEND_TYPE: ${STEND}
    IXORA_CLUSTER_NAME: k8s-ixora-main
    
    WERF_SYNCHRONIZATION: kubernetes://gitlab-ci

    WERF_CONFIG: clusters/${IXORA_CLUSTER_NAME}/werf.yml 

    # передаем Helm наше описание solution + stend-type как значения переменных (для шаблонизации)
    WERF_VALUES_SOLUTION: solutions/${IXORA_CICD_SOLUTION}/${IXORA_CICD_SOLUTION}.yml
    WERF_VALUES_STEND:    solutions/${IXORA_CICD_SOLUTION}/stend-${IXORA_CICD_STEND_TYPE}.yml
    WERF_VALUES_HELM_DIR:    ${CI_PROJECT_DIR}/clusters/${IXORA_CLUSTER_NAME}/.helm
    WERF_VALUES_HELM_CHART:  ${WERF_VALUES_HELM_DIR}/Chart.yaml
    WERF_VALUES_HELM_VALUES:  ${WERF_VALUES_HELM_DIR}/values.yaml

  script:
    - source "$(werf ci-env gitlab --as-file)"
    - werf version
    - werf converge
```
