### ISSUE TITLE
Enable layer-by-layer caching of Dockerfile instructions for all images specified in werf.yaml

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#5974]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

When using Buildah, users can enable layer-by-layer caching of Dockerfile instructions via the staged directive:

```yaml
# werf.yaml
image: example
dockerfile: ./Dockerfile
staged: true
```

However, currently, there is no way to enable this feature globally for all images. This limitation requires users to specify the caching option individually for each image, which can be tedious and error-prone in projects with multiple images.

### Solution (if you have one)

Add the staged option in the meta section of werf.yaml to activate layer-by-layer caching for all images at once.

```yaml
project: app
configVersion: 1
build:
  staged: true
```

### Additional information

Details on layer-by-layer caching can be found in the werf documentation: [werf layer-by-layer caching](https://werf.io/documentation/v1.2/usage/build/process.html#layer-by-layer-image-caching).

**Comment by Bharadwajshivam28** [comment]
Hey @alexey-igrychev I am new and wanted to contribute. 
Can I work on this issue?

**Comment by Bharadwajshivam28** [comment]
Can you please share steps to get started?

**Comment by alexey-igrychev** [comment]
Hello, and thank your interest in this issue! ❤️

- Begin by understanding how the `werf.yaml` configuration is read and processed, then look into how [the current staged directive](https://github.com/werf/werf/blob/main/pkg/config/image_from_dockerfile.go#L21) works for individual images and where it is used. 
- After that, you will have enough knowledge to add the new staged directive under [the build section](https://github.com/werf/werf/blob/main/pkg/config/meta_build.go) and the rest of the code. 
  - Ensure that an image-specific staged setting overrides the common one, maintaining flexibility for individual configurations:
     ```yaml
     project: app
     configVersion: 1
     build:
       staged: true
     ---
     image: example
     dockerfile: ./Dockerfile
     staged: false
     ``` 
- Finally, you should update documentation [here](https://werf.io/documentation/v1.2/reference/werf_yaml.html#L4) and [here](https://werf.io/documentation/v1.2/usage/build/process.html#dockerfile).

> Layer-by-layer caching works only with the Buildah backend and you can find the necessary setup instructions [here](https://werf.io/documentation/v1.2/?usage=localDev&os=linux&buildBackend=buildah).

Don't hesitate to reach out if you have any questions or need help along the way. 🙌🏼
