### ISSUE TITLE
goTemplateRendering env function not working

### ISSUE THREAD

**Issue by abrekhov** [werf/werf#6165]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

1.2.303

### How to reproduce

1. set werf.yaml
```yaml
project: test
configVersion: 1
---
image: test
dockerfile: Dockerfile
staged: true
args:
  CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX: '{{ env "CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX" "docker.io" }}'
```

2. Allow env function in werf-giterminism 

```yaml
giterminismConfigVersion: 1
config:
  dockerfile:
    allowContextAddFiles: [".npmrc"]
  goTemplateRendering:
    allowEnvVariables: ["CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX"]
```

3. Set `.gitlab-ci.yaml`

```yaml
 script:
    - source $(werf ci-env gitlab --as-file)
    - export
    - CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX=$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX werf build --repo $WERF_REPO --add-custom-tag=%image%-$CI_COMMIT_REF_SLUG
```

### Result

```
$ CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX=$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX werf build --repo $WERF_REPO --add-custom-tag=%image%-$CI_COMMIT_REF_SLUG
Version: v1.2.303
Using project dir: /builds/platform/test
Using werf config render file: /tmp/werf-config-render-2365218990
⛵ image test
00:00
┌ ⛵ image test
└ ⛵ image test (0.00 seconds) FAILED
Running time 0.36 seconds
Error: phase build before image test stages handler failed: unable to setup base image: unable to get base image "/node:21.1.0-slim" manifest: error getting buildah inspect of "/node:21.1.0-slim": error doing inspect: error getting builder from image "/node:21.1.0-slim": importing settings: invalid reference format
```

### Expected result

Sucсessfull build
