### ISSUE TITLE
Helm dependency download error

### ISSUE THREAD

**Issue by smilingDima** [werf/werf#6323]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

2.9.1

### How to reproduce

My Chart.yaml:
```
apiVersion: v2
dependencies:
- name: postgresql-ha
  version: "~14.2.18"
  repository: oci://registry-1.docker.io/bitnamicharts
```

### Result

When I make `werf coverage` - I get this error:

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x568631]
> goroutine 1 [running]:
> os.(*File).Fd(...)

![image](https://github.com/user-attachments/assets/5534465d-4618-4121-8b28-6e678b6aed5d)

### Expected result

No errors

### Additional information

Maybe this will help solve the problem:
![image](https://github.com/user-attachments/assets/9c78814c-7c4c-45e5-912a-3b30c21763f6)
