### ISSUE TITLE
Наследование и импортирование файлов работает не как ожидается

### ISSUE THREAD

**Issue by karabanov** [werf/werf#6329]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

v2.10.5

### How to reproduce

В разделе документации "[Взаимодействие между образами](https://ru.werf.io/docs/v2/usage/build/images.html#%D0%B2%D0%B7%D0%B0%D0%B8%D0%BC%D0%BE%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B5-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%B0%D0%BC%D0%B8)" предлагается возможность копировать файлы из промежуточного образа в финальный причём промежуточный и финальный образ могут быть описаны в независимых Dockerfile, но работает это не совсем так, как ожидается.

Передаю `BUILDER_IMAGE_NAME` в качестве аргумента в целевой образ:

```
---
image: builder
context: .
dockerfile: .werf/builder/builder.Dockerfile
---
image: nginx
context: .
dockerfile: .werf/nginx/nginx.Dockerfile
final: true
args:
  APP_NGINX_IMAGE_TAG: {{ $app_nginx_image_tag }}
dependencies:
  - image: builder
    imports:
      - type: ImageName
        targetBuildArg: BUILDER_IMAGE_NAME
```

И он точно передайтся - вывел все переменные окружения в лог:

```
8.921673702s 8.897469077s │ │ │ nginx/dockerfile  Step 6/17 : RUN env
9.022755353s 8.979686438s │ │ │ nginx/dockerfile   ---> Running in 51c9a088a401
9.224573013s 9.189327987s │ │ │ nginx/dockerfile  HOSTNAME=51c9a088a401
9.224583249s 9.189333538s │ │ │ nginx/dockerfile  HOME=/root
9.224693788s 9.189337449s │ │ │ nginx/dockerfile  TERM=xterm-256color
9.224705327s 9.189341648s │ │ │ nginx/dockerfile  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9.2248138s   9.189574476s │ │ │ nginx/dockerfile  DEBIAN_FRONTEND=noninteractive
9.224826049s 9.189601073s │ │ │ nginx/dockerfile  BUILDER_IMAGE_NAME=cr.example.com/my-app:8f4b5bfa8925bc00e1ecdc9882f3883963e8d88e8900136a9c56a6aa-1725360012873
9.22486342s  9.189614646s │ │ │ nginx/dockerfile  PWD=/
```

Далее пытаюсь скопировать артефакты из промежуточного образа хоть куда-то в финальный образ:

```
COPY --from=${BUILDER_IMAGE_NAME} /build /tmp/
```

И получаю:

```
Error: phase build on image nginx stage dockerfile handler failed: failed to build image for stage dockerfile with digest 38e7e6890d02e6e5da9cd3a888c0275247124271eb85b88274d0d1e8: error building dockerfile with docker-server-backend: Status: invalid from flag value ${BUILDER_IMAGE_NAME}: invalid reference format: repository name (library/${BUILDER_IMAGE_NAME}) must be lowercase, Code:
```

Если я руками впишу имя промежуточного образа, то всё соберётся корректно и файлы действительно скопируются:

```
COPY --from=cr.example.com/my-app:8f4b5bfa8925bc00e1ecdc9882f3883963e8d88e8900136a9c56a6aa-1725360012873 /build /tmp/
```

@alexey-igrychev предложил немного изменить Dockerfile финального образа примерно так:
```
ARG BUILDER_IMAGE_NAME
FROM $BUILDER_IMAGE_NAME as builder

FROM nginx:1.26.1-alpine
COPY --from=builder /build /tmp/
```

И это сработало - файлы дествительно скопировались, но перестала работать передача аргументов и стало невозможно указать тег базового образа с помощью аргумента `$APP_NGINX_IMAGE_TAG`

Вот [репозиторий с минималистичным проектом](https://github.com/karabanov/arg_pass_werf_bug), в котором воспроизводится баг.

### Result

```
Error: phase build on image nginx stage dockerfile handler failed: failed to build image for stage dockerfile with digest 9399422d99bec6cf9d2a4963a8a39bd40e1266fb85cff967d07c50df: error building dockerfile with docker-server-backend: Status: invalid from flag value ${BUILDER_IMAGE_NAME}: invalid reference format: repository name (library/${BUILDER_IMAGE_NAME}) must be lowercase, Code: 1
```

### Expected result

Всё аргументы успешно передаются в финальный образ и есть возможность скопирвоать файлы из промежуточного образа в финальный

### Additional information

[Обсуждение в Telegram группе @werf_ru](https://t.me/werf_ru/41461)

**Comment by karabanov** [comment]
Провёл ряд экспериментов и могу чуть точнее описать происходящее - если в описании образа в werf.yaml присутствует одновременно передача аргументов в секции `args:` и передача параметров промежуточного образа в секции `dependencies:`, то точно сборка точно упадёт

Пример:
```
---
image: builder
context: .
dockerfile: .werf/builder/builder.Dockerfile
final: false
args:
  APP_PHP_VERSION: {{ $app_php_version }}
  APP_PHP_IMAGE_TAG: {{ $app_php_image_tag }}
---
image: nginx
context: .
dockerfile: .werf/nginx/nginx.Dockerfile
args:
  APP_NGINX_IMAGE_TAG: {{ $app_nginx_image_tag }}
dependencies:
  - image: builder
    imports:
      - type: ImageName
        targetBuildArg: BUILDER_IMAGE_NAME
```

Если закомментировать секцию `args:`
```
---
image: builder
context: .
dockerfile: .werf/builder/builder.Dockerfile
final: false
args:
  APP_PHP_VERSION: {{ $app_php_version }}
  APP_PHP_IMAGE_TAG: {{ $app_php_image_tag }}
---
image: nginx
context: .
dockerfile: .werf/nginx/nginx.Dockerfile
# args:
#  APP_NGINX_IMAGE_TAG: {{ $app_nginx_image_tag }}
dependencies:
  - image: builder
    imports:
      - type: ImageName
        targetBuildArg: BUILDER_IMAGE_NAME
```

A в Dockerfile финального образа написать:
```
ARG BUILDER_IMAGE_NAME
FROM $BUILDER_IMAGE_NAME AS builder

FROM cr.example.com/nginx-sury:явно_указанный_тег
COPY --from=builder /build /tmp/
RUN ls -alah /tmp/
```

То сборка пройдёт успешно.

Подозреваю, что аргументы из `dependencies:` и аргументы из `args:`, как-то конфликтуют.

**Comment by karabanov** [comment]
Попробовал собрать с помощью Buildah:

```
Error: phase build on image nginx stage dockerfile handler failed: unable to fetch dependencies for stage nginx/dockerfile: error getting buildah inspect of "cr.example.com/nginx:": error doing inspect: error getting builder from image "cr.example.com/nginx:": importing settings: invalid reference format
```

Похоже аргумент `APP_NGINX_IMAGE_TAG` не пробрасывается.

werf.yaml:

```
---
image: builder
context: .
dockerfile: .werf/builder/builder.Dockerfile
final: false
args:
  APP_PHP_VERSION: {{ $app_php_version }}
  APP_PHP_IMAGE_TAG: {{ $app_php_image_tag }}
---
image: nginx
context: .
dockerfile: .werf/nginx/nginx.Dockerfile
args:
  APP_NGINX_IMAGE_TAG: {{ $app_nginx_image_tag }}
dependencies:
  - image: builder
    imports:
      - type: ImageName
        targetBuildArg: BUILDER_IMAGE_NAME
```

Dockerfile:

```
ARG BUILDER_IMAGE_NAME
FROM $BUILDER_IMAGE_NAME AS builder

ARG APP_NGINX_IMAGE_TAG
FROM cr.example.com/nginx:${APP_NGINX_IMAGE_TAG}

COPY --from=builder /build /tmp
```
