### ISSUE TITLE
Could not delete default keys from subcharts if subchart is defined in dependencies

### ISSUE THREAD

**Issue by shcherbak** [werf/werf#6353]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

2.10.9, 1.2.329

### How to reproduce

Could not delete default keys from subcharts if subchart is defined in dependencies

if subchart has for example
```
resources:
  limits:
    cpu: 4
    memory: 3Gi
  requests:
     cpu: 700m
     memory: 70Mi
```
it is unable to override with
```
resources:
  limits: null
  requests: null
```

the same as https://github.com/helm/helm/issues/9027

### Result

default values are in rendered files

### Expected result

default values are overrided
