### ISSUE TITLE
Allow export-values in Chart.yaml to export variable into Lists in YAML

### ISSUE THREAD

**Issue by petrovvitalik** [werf/werf#6567]
### Before proceeding

- [x] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

Currently, it is not possible to export variables into lists in child subcharts.

**Example Parent Chart.yaml:**
```
apiVersion: v2
name: test-nginx
version: 1.1
dependencies:
- name: test-nginx-child
  version: 1.0
  export-values:
    - parent: werf.env
      child: nginx.nginxUserDeployments.deployments[2].test.text
```

**Values after werf converge:**
```
test-nginx-child:
  global:
    env: dev
    werf:
      name: test-nginx
      version: v2.16.1+fix1
  nginx:
    nginxUserDeployments:
      deployments:
        - name: deployment-1
          test:
            text: text1
        - name: deployment-2
          test:
            text: not exported
        - name: deployment-3
          test:
            text: default
      deployments[2]:
        test:
          text: dev
```

**As a result, it is very difficult to pass werf.image.name to dependent helm chart.**
Of course, there is a possibility to use --set, but it requires to generate build report, export variables from it and complicates deployment process.

Could you please extend functionality of export-values and make it possible to use it with lists in dependant charts?
Thanks a lot.

### Solution (if you have one)

My demo repository that somehow explains this problem:
https://github.com/petrovvitalik/test-nginx

The Helm chart that I am using as a dependency and struggling with:
https://github.com/dagster-io/dagster/tree/master/helm/dagster
