### ISSUE TITLE
werf behind (via) proxy

### ISSUE THREAD

**Issue by nohnaimer** [werf/werf#6616]
### Before proceeding

- [x] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

werf does not work through proxy

### Solution (if you have one)

I use werf in docker image registry.werf.io/werf/werf:2-stable
I try:
export HTTP_PROXY=my_proxy
export HTTPS_PROXY=my_proxy
HTTP_PROXY=my_proxy HTTPS_PROXY=my_proxy werf ....

### Additional information

Any solution? O maybe I don't find setting for proxy?

**Comment by alexey-igrychev** [comment]
Thank you for your feedback! We will consider this.

**Comment by alexey-igrychev** [comment]
werf's own HTTPS traffic goes through transports that honour `HTTP_PROXY`/`HTTPS_PROXY`/`NO_PROXY`, so this should work out of the box. To move forward we need specifics: which command, what exactly fails (full error output with `--log-debug`), and whether the proxy needs authentication or a custom CA.

**Comment by nohnaimer** [comment]
Hi,
I try build with Gitlab CI/CD in docker. Log:
<img width="2450" height="1163" alt="Image" src="https://github.com/user-attachments/assets/e64b0a4d-c2fb-4338-9509-c4bd5adb6d74" />
On my Gitlab add proxy settings without auth like environment variables on all repository:
HTTP_PROXY=http://proxy:3128
HTTPS_PROXY=http://proxy:3128
NO_PROXY=localhost,127.0.0.1
http_proxy=http://proxy:3128
https_proxy=http://proxy:3128
no_proxy=localhost,127.0.0.1

When start pipeline and start command source "$(werf ci-env gitlab --as-file)" all variables put in container but packages still not installed.

I try export command before start werf command and same result.
I try like this:
```yaml
image:build:
  stage: build
  image: registry.werf.io/werf/werf:2-stable
  variables:
    WERF_CACHE: "/cache/werf"
    HTTP_PROXY:  http://proxy:3128
    HTTPS_PROXY:  http://proxy:3128
    NO_PROXY: localhost,127.0.0.1
    http_proxy:  http://proxy:3128
    https_proxy:  http://proxy:3128
    no_proxy: localhost,127.0.0.1
```

Maybe need another method add proxy settings for werf container?
