### ISSUE TITLE
Add service value to indicate whether the image was rebuilt since last time

### ISSUE THREAD

**Issue by ilya-lesikov** [werf/werf#6741]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

Hard to check whether the image was rebuilt since last time. Example use case: K8s Job should rebuild/reupload remote assets, but only when the original image was changed.

### Solution (if you have one)

```yaml
werf:
  changed:
    backend: true
    frontend: false
```
